# Generated by Django 5.0.14 on 2026-01-30 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.CharField(help_text='User ID dari SSO token', max_length=255)),
                ('user_message', models.TextField()),
                ('response_text', models.TextField()),
                ('response_chart_json', models.JSONField(blank=True, null=True)),
                ('document_ids', models.JSONField(blank=True, help_text='Array of document IDs yang digunakan sebagai konteks', null=True)),
                ('conversation_id', models.CharField(blank=True, help_text='ID untuk mengelompokkan percakapan', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'chat_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_user_id', '-created_at'], name='chat_logs_owner_u_6c23e4_idx'), models.Index(fields=['conversation_id', '-created_at'], name='chat_logs_convers_926464_idx')],
            },
        ),
    ]
