# Generated by Django 5.0.14 on 2026-01-30 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.CharField(help_text='User ID dari SSO token (untuk audit/ownership)', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(help_text='Teks hasil ekstraksi dokumen')),
                ('source_filename', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('content_length', models.IntegerField(blank=True, help_text='Panjang konten dalam bytes', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_user_id', '-created_at'], name='documents_owner_u_a6e00b_idx')],
            },
        ),
    ]
