# Generated by Django 5.0.14 on 2026-02-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Data terstruktur (misalnya tabel dari Excel)', null=True),
        ),
    ]
